-- Delete relational tables (children that depend on the most ancestors)
DROP TABLE EXERCISE_VIDEO_URL CASCADE;
DROP TABLE HAS_PROGRAM CASCADE;
DROP TABLE INCLUDES CASCADE;

-- Delete tables that depend on the trainee or programs
DROP TABLE LOCKER CASCADE;
DROP TABLE WORKOUT_LOG CASCADE;
DROP TABLE TRAINEE_GOAL CASCADE;
DROP TABLE BODY_MEASUREMENT CASCADE;
DROP TABLE HEALTH_DECLARATION CASCADE;

-- Delete parent tables
DROP TABLE TRAINEE_PROFILE CASCADE;
DROP TABLE NUTRITION_MENU CASCADE;
DROP TABLE TRAINING_PROGRAM CASCADE;
DROP TABLE EXERCISE CASCADE;
DROP TABLE MUSCLE_GROUP CASCADE;