INSERT INTO EXERCISE (Exercise_ID, Exercise_Name, Equipment_Needed, Instructions, Calories_Burned_Per_Minute, Muscle_Group_Id) VALUES
(1, 'Resistance Band Close-Grip Core Press', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 8.57, 10),
(2, 'Resistance Band Glutes Squat', 'Resistance Band', 'Maintain proper form and control the weight.', 10.41, 9),
(3, 'Resistance Band Incline Triceps Press', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 3.56, 5),
(4, 'Smith Machine Biceps Pull-down', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 10.93, 4),
(5, 'Cable Single-Leg Forearms Pull-down', 'Cable', 'Perform the movement in a slow, controlled manner.', 12.79, 11),
(6, 'Kettlebell Seated Biceps Curl', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 14.12, 4),
(7, 'Medicine Ball Single-Arm Chest Lunge', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 11.83, 1),
(8, 'Barbell Flat Biceps Push-down', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 12.64, 4),
(9, 'Kettlebell Wide-Grip Calves Press', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 11.01, 8),
(10, 'Machine Alternating Core Deadlift', 'Machine', 'Keep your core tight and back straight during the movement.', 12.24, 10),
(11, 'Dumbbell Decline Back Fly', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 12.21, 2),
(12, 'Smith Machine Shoulders Raise', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 5.81, 3),
(13, 'Smith Machine Chest Row', 'Smith Machine', 'Ensure full range of motion for maximum benefit.', 13.77, 1),
(14, 'Medicine Ball Reverse Traps Push-down', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 3.0, 12),
(15, 'Kettlebell Hamstrings Lunge', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 14.88, 7),
(16, 'Smith Machine Triceps Shrug', 'Smith Machine', 'Maintain proper form and control the weight.', 7.46, 5),
(17, 'Machine Single-Arm Forearms Hold', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 13.31, 11),
(18, 'Machine Forearms Crunch', 'Machine', 'Maintain proper form and control the weight.', 11.55, 11),
(19, 'Medicine Ball Close-Grip Traps Hold', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 8.14, 12),
(20, 'Smith Machine Back Pull-down', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 7.32, 2),
(21, 'Machine Close-Grip Triceps Squat', 'Machine', 'Ensure full range of motion for maximum benefit.', 6.16, 5),
(22, 'Medicine Ball Seated Core Squat', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 11.92, 10),
(23, 'Resistance Band Core Hold', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 5.7, 10),
(24, 'Cable Standing Traps Kickback', 'Cable', 'Squeeze the target muscle at the top of the movement.', 6.12, 12),
(25, 'Resistance Band Lats Shrug', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 8.2, 13),
(26, 'Medicine Ball Lats Raise', 'Medicine Ball', 'Maintain proper form and control the weight.', 14.85, 13),
(27, 'Resistance Band Incline Calves Squat', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 9.63, 8),
(28, 'Kettlebell Quadriceps Kickback', 'Kettlebell', 'Keep your core tight and back straight during the movement.', 11.51, 6),
(29, 'Kettlebell Incline Quadriceps Raise', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 4.08, 6),
(30, 'Cable Lats Push-down', 'Cable', 'Keep your core tight and back straight during the movement.', 4.65, 13),
(31, 'Resistance Band Core Deadlift', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 8.0, 10),
(32, 'Smith Machine Glutes Push-down', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 12.89, 9),
(33, 'Kettlebell Chest Curl', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 9.41, 1),
(34, 'Cable Reverse Shoulders Lunge', 'Cable', 'Ensure full range of motion for maximum benefit.', 12.98, 3),
(35, 'Smith Machine Single-Arm Back Raise', 'Smith Machine', 'Squeeze the target muscle at the top of the movement.', 5.79, 2),
(36, 'Barbell Standing Core Row', 'Barbell', 'Keep your core tight and back straight during the movement.', 3.31, 10),
(37, 'Machine Calves Extension', 'Machine', 'Ensure full range of motion for maximum benefit.', 5.15, 8),
(38, 'Bodyweight Close-Grip Traps Extension', 'Bodyweight', 'Maintain proper form and control the weight.', 12.35, 12),
(39, 'Barbell Biceps Row', 'Barbell', 'Maintain proper form and control the weight.', 6.97, 4),
(40, 'Cable Shoulders Shrug', 'Cable', 'Breathe out on the exertion phase and inhale on the way down.', 14.91, 3),
(41, 'Machine Chest Shrug', 'Machine', 'Maintain proper form and control the weight.', 13.87, 1),
(42, 'Barbell Wide-Grip Calves Shrug', 'Barbell', 'Ensure full range of motion for maximum benefit.', 13.31, 8),
(43, 'Medicine Ball Traps Raise', 'Medicine Ball', 'Perform the movement in a slow, controlled manner.', 12.33, 12),
(44, 'Barbell Standing Core Shrug', 'Barbell', 'Keep your core tight and back straight during the movement.', 12.91, 10),
(45, 'Barbell Core Fly', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 11.61, 10),
(46, 'Bodyweight Close-Grip Calves Crunch', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 3.04, 8),
(47, 'Resistance Band Triceps Push-down', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 6.86, 5),
(48, 'Dumbbell Seated Core Raise', 'Dumbbell', 'Maintain proper form and control the weight.', 4.4, 10),
(49, 'Cable Triceps Deadlift', 'Cable', 'Perform the movement in a slow, controlled manner.', 6.92, 5),
(50, 'Smith Machine Quadriceps Shrug', 'Smith Machine', 'Keep your elbows tucked in and avoid swinging.', 8.07, 6),
(51, 'Smith Machine Forearms Push-down', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 11.65, 11),
(52, 'Cable Shoulders Fly', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 11.67, 3),
(53, 'Barbell Biceps Curl', 'Barbell', 'Perform the movement in a slow, controlled manner.', 6.76, 4),
(54, 'Smith Machine Hamstrings Curl', 'Smith Machine', 'Maintain proper form and control the weight.', 3.52, 7),
(55, 'Bodyweight Biceps Raise', 'Bodyweight', 'Breathe out on the exertion phase and inhale on the way down.', 14.04, 4),
(56, 'Machine Biceps Crunch', 'Machine', 'Breathe out on the exertion phase and inhale on the way down.', 9.64, 4),
(57, 'Smith Machine Single-Leg Chest Press', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 3.7, 1),
(58, 'Kettlebell Glutes Kickback', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 7.75, 9),
(59, 'Machine Alternating Biceps Row', 'Machine', 'Ensure full range of motion for maximum benefit.', 8.06, 4),
(60, 'Barbell Decline Glutes Row', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 4.9, 9),
(61, 'Resistance Band Biceps Raise', 'Resistance Band', 'Breathe out on the exertion phase and inhale on the way down.', 11.82, 4),
(62, 'Bodyweight Triceps Pull-down', 'Bodyweight', 'Keep your elbows tucked in and avoid swinging.', 10.29, 5),
(63, 'Medicine Ball Reverse Quadriceps Pull-down', 'Medicine Ball', 'Perform the movement in a slow, controlled manner.', 10.41, 6),
(64, 'Kettlebell Biceps Curl', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 13.93, 4),
(65, 'Kettlebell Single-Arm Back Extension', 'Kettlebell', 'Maintain proper form and control the weight.', 13.21, 2),
(66, 'Bodyweight Chest Crunch', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 4.45, 1),
(67, 'Machine Lats Deadlift', 'Machine', 'Ensure full range of motion for maximum benefit.', 7.34, 13),
(68, 'Resistance Band Chest Kickback', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 14.79, 1),
(69, 'Resistance Band Single-Arm Hamstrings Kickback', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 13.99, 7),
(70, 'Barbell Shoulders Raise', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 12.79, 3),
(71, 'Barbell Forearms Row', 'Barbell', 'Ensure full range of motion for maximum benefit.', 6.66, 11),
(72, 'Bodyweight Seated Biceps Row', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 10.4, 4),
(73, 'Machine Glutes Deadlift', 'Machine', 'Keep your core tight and back straight during the movement.', 11.79, 9),
(74, 'Machine Wide-Grip Hamstrings Push-down', 'Machine', 'Maintain proper form and control the weight.', 6.75, 7),
(75, 'Resistance Band Hamstrings Crunch', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 6.58, 7),
(76, 'Bodyweight Triceps Push-down', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 12.03, 5),
(77, 'Medicine Ball Core Extension', 'Medicine Ball', 'Maintain proper form and control the weight.', 11.09, 10),
(78, 'Cable Lats Lunge', 'Cable', 'Perform the movement in a slow, controlled manner.', 14.2, 13),
(79, 'Resistance Band Single-Leg Calves Squat', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 7.9, 8),
(80, 'Smith Machine Standing Core Extension', 'Smith Machine', 'Ensure full range of motion for maximum benefit.', 14.76, 10),
(81, 'Dumbbell Alternating Quadriceps Deadlift', 'Dumbbell', 'Keep your core tight and back straight during the movement.', 11.86, 6),
(82, 'Resistance Band Reverse Lats Lunge', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 10.8, 13),
(83, 'Smith Machine Forearms Lunge', 'Smith Machine', 'Keep your elbows tucked in and avoid swinging.', 5.38, 11),
(84, 'Dumbbell Glutes Curl', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 7.12, 9),
(85, 'Smith Machine Quadriceps Push-down', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 3.52, 6),
(86, 'Kettlebell Standing Triceps Deadlift', 'Kettlebell', 'Maintain proper form and control the weight.', 10.2, 5),
(87, 'Machine Alternating Calves Row', 'Machine', 'Keep your core tight and back straight during the movement.', 5.8, 8),
(88, 'Dumbbell Biceps Deadlift', 'Dumbbell', 'Keep your core tight and back straight during the movement.', 12.54, 4),
(89, 'Cable Biceps Fly', 'Cable', 'Ensure full range of motion for maximum benefit.', 13.72, 4),
(90, 'Dumbbell Standing Calves Deadlift', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 6.79, 8),
(91, 'Bodyweight Alternating Forearms Extension', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 6.5, 11),
(92, 'Machine Core Fly', 'Machine', 'Maintain proper form and control the weight.', 5.24, 10),
(93, 'Cable Flat Back Deadlift', 'Cable', 'Maintain proper form and control the weight.', 8.14, 2),
(94, 'Smith Machine Seated Lats Press', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 8.65, 13),
(95, 'Machine Core Lunge', 'Machine', 'Ensure full range of motion for maximum benefit.', 7.97, 10),
(96, 'Barbell Quadriceps Curl', 'Barbell', 'Ensure full range of motion for maximum benefit.', 11.55, 6),
(97, 'Kettlebell Triceps Extension', 'Kettlebell', 'Maintain proper form and control the weight.', 7.89, 5),
(98, 'Resistance Band Quadriceps Extension', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 6.01, 6),
(99, 'Dumbbell Single-Leg Shoulders Pull-down', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 12.22, 3),
(100, 'Barbell Seated Back Push-down', 'Barbell', 'Keep your elbows tucked in and avoid swinging.', 7.13, 2),
(101, 'Kettlebell Seated Chest Push-down', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 5.62, 1),
(102, 'Medicine Ball Single-Leg Glutes Crunch', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 14.27, 9),
(103, 'Dumbbell Traps Deadlift', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 4.94, 12),
(104, 'Bodyweight Biceps Curl', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 12.48, 4),
(105, 'Kettlebell Decline Shoulders Fly', 'Kettlebell', 'Keep your core tight and back straight during the movement.', 10.44, 3),
(106, 'Resistance Band Single-Leg Calves Crunch', 'Resistance Band', 'Breathe out on the exertion phase and inhale on the way down.', 10.57, 8),
(107, 'Medicine Ball Chest Row', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 5.94, 1),
(108, 'Cable Single-Leg Lats Kickback', 'Cable', 'Ensure full range of motion for maximum benefit.', 7.04, 13),
(109, 'Resistance Band Forearms Curl', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 12.17, 11),
(110, 'Barbell Shoulders Shrug', 'Barbell', 'Maintain proper form and control the weight.', 5.44, 3),
(111, 'Cable Calves Crunch', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 11.28, 8),
(112, 'Barbell Close-Grip Shoulders Shrug', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 5.71, 3),
(113, 'Medicine Ball Reverse Calves Kickback', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 6.95, 8),
(114, 'Kettlebell Glutes Lunge', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 5.0, 9),
(115, 'Dumbbell Calves Kickback', 'Dumbbell', 'Keep your core tight and back straight during the movement.', 11.97, 8),
(116, 'Resistance Band Single-Arm Calves Push-down', 'Resistance Band', 'Maintain proper form and control the weight.', 12.17, 8),
(117, 'Dumbbell Quadriceps Press', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 12.8, 6),
(118, 'Dumbbell Wide-Grip Quadriceps Squat', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 5.69, 6),
(119, 'Dumbbell Shoulders Squat', 'Dumbbell', 'Breathe out on the exertion phase and inhale on the way down.', 5.56, 3),
(120, 'Machine Alternating Quadriceps Kickback', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 7.22, 6),
(121, 'Kettlebell Close-Grip Triceps Kickback', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 4.82, 5),
(122, 'Kettlebell Wide-Grip Back Push-down', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 6.43, 2),
(123, 'Resistance Band Incline Chest Extension', 'Resistance Band', 'Maintain proper form and control the weight.', 12.36, 1),
(124, 'Kettlebell Single-Arm Back Deadlift', 'Kettlebell', 'Maintain proper form and control the weight.', 3.47, 2),
(125, 'Medicine Ball Incline Chest Lunge', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 8.95, 1),
(126, 'Barbell Quadriceps Extension', 'Barbell', 'Perform the movement in a slow, controlled manner.', 5.94, 6),
(127, 'Machine Wide-Grip Biceps Row', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 13.22, 4),
(128, 'Kettlebell Standing Chest Pull-down', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 5.26, 1),
(129, 'Machine Quadriceps Pull-down', 'Machine', 'Perform the movement in a slow, controlled manner.', 14.57, 6),
(130, 'Dumbbell Forearms Push-down', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 11.89, 11),
(131, 'Smith Machine Lats Deadlift', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 12.27, 13),
(132, 'Machine Incline Back Pull-down', 'Machine', 'Perform the movement in a slow, controlled manner.', 9.18, 2),
(133, 'Bodyweight Shoulders Squat', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 3.28, 3),
(134, 'Barbell Quadriceps Fly', 'Barbell', 'Keep your core tight and back straight during the movement.', 4.29, 6),
(135, 'Cable Incline Biceps Fly', 'Cable', 'Maintain proper form and control the weight.', 6.24, 4),
(136, 'Dumbbell Incline Quadriceps Squat', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 9.26, 6),
(137, 'Barbell Seated Quadriceps Hold', 'Barbell', 'Perform the movement in a slow, controlled manner.', 11.0, 6),
(138, 'Bodyweight Calves Raise', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 4.14, 8),
(139, 'Bodyweight Wide-Grip Calves Kickback', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 6.9, 8),
(140, 'Machine Decline Forearms Squat', 'Machine', 'Perform the movement in a slow, controlled manner.', 9.46, 11),
(141, 'Bodyweight Single-Leg Forearms Kickback', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 9.42, 11),
(142, 'Smith Machine Traps Row', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 8.8, 12),
(143, 'Cable Chest Deadlift', 'Cable', 'Keep your core tight and back straight during the movement.', 10.14, 1),
(144, 'Cable Seated Traps Lunge', 'Cable', 'Keep your core tight and back straight during the movement.', 9.36, 12),
(145, 'Medicine Ball Standing Forearms Squat', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 8.43, 11),
(146, 'Resistance Band Traps Crunch', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 6.18, 12),
(147, 'Machine Triceps Push-down', 'Machine', 'Keep your core tight and back straight during the movement.', 11.72, 5),
(148, 'Cable Wide-Grip Chest Pull-down', 'Cable', 'Ensure full range of motion for maximum benefit.', 3.27, 1),
(149, 'Dumbbell Single-Arm Lats Kickback', 'Dumbbell', 'Keep your core tight and back straight during the movement.', 8.98, 13),
(150, 'Medicine Ball Seated Hamstrings Crunch', 'Medicine Ball', 'Maintain proper form and control the weight.', 9.1, 7),
(151, 'Resistance Band Back Press', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 5.42, 2),
(152, 'Bodyweight Biceps Squat', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 11.97, 4),
(153, 'Bodyweight Incline Hamstrings Kickback', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 3.78, 7),
(154, 'Dumbbell Close-Grip Back Deadlift', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 8.23, 2),
(155, 'Resistance Band Reverse Core Push-down', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 11.34, 10),
(156, 'Kettlebell Alternating Lats Kickback', 'Kettlebell', 'Maintain proper form and control the weight.', 11.66, 13),
(157, 'Medicine Ball Incline Chest Kickback', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 13.45, 1),
(158, 'Smith Machine Biceps Squat', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 3.68, 4),
(159, 'Bodyweight Decline Quadriceps Raise', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 8.9, 6),
(160, 'Machine Forearms Row', 'Machine', 'Ensure full range of motion for maximum benefit.', 5.25, 11),
(161, 'Smith Machine Standing Back Shrug', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 11.24, 2),
(162, 'Machine Calves Deadlift', 'Machine', 'Keep your core tight and back straight during the movement.', 10.23, 8),
(163, 'Medicine Ball Seated Back Squat', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 13.89, 2),
(164, 'Bodyweight Shoulders Deadlift', 'Bodyweight', 'Keep your elbows tucked in and avoid swinging.', 3.91, 3),
(165, 'Machine Lats Press', 'Machine', 'Breathe out on the exertion phase and inhale on the way down.', 10.69, 13),
(166, 'Barbell Single-Leg Traps Lunge', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 6.07, 12),
(167, 'Resistance Band Seated Glutes Press', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 11.54, 9),
(168, 'Kettlebell Quadriceps Curl', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 3.68, 6),
(169, 'Barbell Chest Hold', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 13.66, 1),
(170, 'Resistance Band Triceps Hold', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 4.87, 5),
(171, 'Dumbbell Chest Hold', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 7.24, 1),
(172, 'Kettlebell Reverse Triceps Raise', 'Kettlebell', 'Maintain proper form and control the weight.', 7.83, 5),
(173, 'Medicine Ball Hamstrings Lunge', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 11.9, 7),
(174, 'Medicine Ball Reverse Chest Press', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 14.57, 1),
(175, 'Medicine Ball Reverse Biceps Row', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 4.27, 4),
(176, 'Resistance Band Forearms Fly', 'Resistance Band', 'Maintain proper form and control the weight.', 5.46, 11),
(177, 'Medicine Ball Alternating Chest Curl', 'Medicine Ball', 'Maintain proper form and control the weight.', 3.79, 1),
(178, 'Cable Wide-Grip Glutes Deadlift', 'Cable', 'Squeeze the target muscle at the top of the movement.', 5.93, 9),
(179, 'Smith Machine Hamstrings Row', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 10.53, 7),
(180, 'Kettlebell Chest Row', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 8.53, 1),
(181, 'Machine Quadriceps Curl', 'Machine', 'Perform the movement in a slow, controlled manner.', 3.42, 6),
(182, 'Resistance Band Standing Shoulders Raise', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 7.18, 3),
(183, 'Machine Wide-Grip Triceps Squat', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 11.29, 5),
(184, 'Barbell Single-Arm Chest Push-down', 'Barbell', 'Ensure full range of motion for maximum benefit.', 12.72, 1),
(185, 'Resistance Band Shoulders Row', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 7.21, 3),
(186, 'Smith Machine Traps Extension', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 7.93, 12),
(187, 'Kettlebell Close-Grip Triceps Extension', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 11.44, 5),
(188, 'Resistance Band Glutes Press', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 12.24, 9),
(189, 'Smith Machine Decline Chest Squat', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 13.98, 1),
(190, 'Barbell Glutes Pull-down', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 4.81, 9),
(191, 'Cable Hamstrings Extension', 'Cable', 'Maintain proper form and control the weight.', 4.78, 7),
(192, 'Medicine Ball Traps Curl', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 9.39, 12),
(193, 'Cable Alternating Hamstrings Fly', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 3.65, 7),
(194, 'Bodyweight Traps Row', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 6.35, 12),
(195, 'Resistance Band Hamstrings Kickback', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 8.99, 7),
(196, 'Machine Alternating Glutes Fly', 'Machine', 'Perform the movement in a slow, controlled manner.', 13.72, 9),
(197, 'Cable Alternating Forearms Squat', 'Cable', 'Maintain proper form and control the weight.', 5.19, 11),
(198, 'Bodyweight Quadriceps Shrug', 'Bodyweight', 'Breathe out on the exertion phase and inhale on the way down.', 10.24, 6),
(199, 'Medicine Ball Back Fly', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 5.65, 2),
(200, 'Resistance Band Single-Leg Quadriceps Extension', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 14.97, 6),
(201, 'Machine Standing Triceps Press', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 14.54, 5),
(202, 'Kettlebell Reverse Forearms Press', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 6.67, 11),
(203, 'Barbell Chest Row', 'Barbell', 'Keep your core tight and back straight during the movement.', 14.24, 1),
(204, 'Medicine Ball Incline Back Raise', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 11.16, 2),
(205, 'Kettlebell Core Squat', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 14.35, 10),
(206, 'Resistance Band Standing Quadriceps Curl', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 7.25, 6),
(207, 'Barbell Chest Pull-down', 'Barbell', 'Ensure full range of motion for maximum benefit.', 12.32, 1),
(208, 'Medicine Ball Quadriceps Row', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 6.62, 6),
(209, 'Cable Single-Leg Chest Fly', 'Cable', 'Squeeze the target muscle at the top of the movement.', 5.43, 1),
(210, 'Machine Calves Curl', 'Machine', 'Maintain proper form and control the weight.', 12.61, 8),
(211, 'Cable Flat Triceps Fly', 'Cable', 'Squeeze the target muscle at the top of the movement.', 10.11, 5),
(212, 'Machine Calves Kickback', 'Machine', 'Ensure full range of motion for maximum benefit.', 4.81, 8),
(213, 'Resistance Band Hamstrings Raise', 'Resistance Band', 'Maintain proper form and control the weight.', 11.26, 7),
(214, 'Bodyweight Single-Leg Forearms Lunge', 'Bodyweight', 'Keep your elbows tucked in and avoid swinging.', 6.12, 11),
(215, 'Kettlebell Quadriceps Fly', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 5.33, 6),
(216, 'Barbell Back Crunch', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 4.9, 2),
(217, 'Bodyweight Triceps Extension', 'Bodyweight', 'Keep your elbows tucked in and avoid swinging.', 7.71, 5),
(218, 'Barbell Biceps Lunge', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 10.11, 4),
(219, 'Barbell Back Shrug', 'Barbell', 'Maintain proper form and control the weight.', 11.77, 2),
(220, 'Resistance Band Close-Grip Core Crunch', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 13.03, 10),
(221, 'Cable Reverse Forearms Curl', 'Cable', 'Ensure full range of motion for maximum benefit.', 14.81, 11),
(222, 'Medicine Ball Quadriceps Press', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 12.52, 6),
(223, 'Kettlebell Quadriceps Extension', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 9.34, 6),
(224, 'Kettlebell Calves Row', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 12.75, 8),
(225, 'Kettlebell Seated Forearms Fly', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 11.16, 11),
(226, 'Bodyweight Triceps Lunge', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 10.29, 5),
(227, 'Kettlebell Reverse Core Curl', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 9.81, 10),
(228, 'Bodyweight Hamstrings Shrug', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 3.7, 7),
(229, 'Barbell Calves Push-down', 'Barbell', 'Keep your core tight and back straight during the movement.', 4.27, 8),
(230, 'Kettlebell Standing Calves Shrug', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 10.35, 8),
(231, 'Dumbbell Close-Grip Forearms Hold', 'Dumbbell', 'Maintain proper form and control the weight.', 10.4, 11),
(232, 'Kettlebell Calves Curl', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 9.24, 8),
(233, 'Barbell Lats Crunch', 'Barbell', 'Keep your elbows tucked in and avoid swinging.', 10.37, 13),
(234, 'Cable Hamstrings Hold', 'Cable', 'Maintain proper form and control the weight.', 9.9, 7),
(235, 'Smith Machine Decline Shoulders Press', 'Smith Machine', 'Squeeze the target muscle at the top of the movement.', 9.49, 3),
(236, 'Dumbbell Single-Arm Quadriceps Pull-down', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 5.87, 6),
(237, 'Kettlebell Triceps Pull-down', 'Kettlebell', 'Maintain proper form and control the weight.', 13.49, 5),
(238, 'Kettlebell Hamstrings Push-down', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 3.1, 7),
(239, 'Resistance Band Lats Raise', 'Resistance Band', 'Maintain proper form and control the weight.', 3.84, 13),
(240, 'Medicine Ball Flat Quadriceps Raise', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 12.18, 6),
(241, 'Bodyweight Single-Arm Triceps Raise', 'Bodyweight', 'Maintain proper form and control the weight.', 13.81, 5),
(242, 'Kettlebell Core Curl', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 11.39, 10),
(243, 'Resistance Band Incline Forearms Fly', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 12.84, 11),
(244, 'Dumbbell Forearms Shrug', 'Dumbbell', 'Breathe out on the exertion phase and inhale on the way down.', 13.05, 11),
(245, 'Kettlebell Traps Kickback', 'Kettlebell', 'Keep your core tight and back straight during the movement.', 8.55, 12),
(246, 'Medicine Ball Decline Hamstrings Kickback', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 7.71, 7),
(247, 'Dumbbell Back Squat', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 12.14, 2),
(248, 'Machine Traps Fly', 'Machine', 'Keep your core tight and back straight during the movement.', 6.67, 12),
(249, 'Kettlebell Traps Lunge', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 10.2, 12),
(250, 'Bodyweight Decline Chest Fly', 'Bodyweight', 'Maintain proper form and control the weight.', 6.58, 1),
(251, 'Barbell Core Hold', 'Barbell', 'Ensure full range of motion for maximum benefit.', 13.53, 10),
(252, 'Medicine Ball Shoulders Curl', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 6.3, 3),
(253, 'Barbell Decline Forearms Fly', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 14.62, 11),
(254, 'Cable Reverse Back Press', 'Cable', 'Ensure full range of motion for maximum benefit.', 8.39, 2),
(255, 'Barbell Reverse Triceps Curl', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 7.8, 5),
(256, 'Medicine Ball Incline Hamstrings Curl', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 13.78, 7),
(257, 'Cable Biceps Crunch', 'Cable', 'Maintain proper form and control the weight.', 10.06, 4),
(258, 'Resistance Band Lats Deadlift', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 3.48, 13),
(259, 'Bodyweight Chest Extension', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 9.28, 1),
(260, 'Medicine Ball Biceps Curl', 'Medicine Ball', 'Perform the movement in a slow, controlled manner.', 11.8, 4),
(261, 'Bodyweight Alternating Hamstrings Hold', 'Bodyweight', 'Breathe out on the exertion phase and inhale on the way down.', 6.17, 7),
(262, 'Smith Machine Traps Curl', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 8.75, 12),
(263, 'Smith Machine Shoulders Crunch', 'Smith Machine', 'Squeeze the target muscle at the top of the movement.', 8.16, 3),
(264, 'Resistance Band Forearms Hold', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 14.46, 11),
(265, 'Bodyweight Reverse Glutes Kickback', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 3.54, 9),
(266, 'Medicine Ball Forearms Shrug', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 4.55, 11),
(267, 'Dumbbell Wide-Grip Glutes Fly', 'Dumbbell', 'Breathe out on the exertion phase and inhale on the way down.', 5.46, 9),
(268, 'Cable Close-Grip Back Press', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 10.49, 2),
(269, 'Resistance Band Chest Pull-down', 'Resistance Band', 'Maintain proper form and control the weight.', 5.19, 1),
(270, 'Medicine Ball Back Push-down', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 5.1, 2),
(271, 'Resistance Band Quadriceps Push-down', 'Resistance Band', 'Breathe out on the exertion phase and inhale on the way down.', 14.98, 6),
(272, 'Smith Machine Back Row', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 9.64, 2),
(273, 'Resistance Band Glutes Pull-down', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 7.42, 9),
(274, 'Cable Alternating Back Lunge', 'Cable', 'Keep your core tight and back straight during the movement.', 5.29, 2),
(275, 'Resistance Band Glutes Hold', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 9.53, 9),
(276, 'Barbell Close-Grip Shoulders Curl', 'Barbell', 'Maintain proper form and control the weight.', 4.64, 3),
(277, 'Barbell Decline Traps Crunch', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 6.02, 12),
(278, 'Cable Glutes Crunch', 'Cable', 'Squeeze the target muscle at the top of the movement.', 5.28, 9),
(279, 'Bodyweight Reverse Back Raise', 'Bodyweight', 'Keep your core tight and back straight during the movement.', 4.43, 2),
(280, 'Barbell Traps Row', 'Barbell', 'Keep your core tight and back straight during the movement.', 11.68, 12),
(281, 'Kettlebell Flat Shoulders Lunge', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 9.27, 3),
(282, 'Medicine Ball Standing Biceps Squat', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 14.44, 4),
(283, 'Dumbbell Reverse Core Hold', 'Dumbbell', 'Breathe out on the exertion phase and inhale on the way down.', 13.51, 10),
(284, 'Machine Triceps Curl', 'Machine', 'Ensure full range of motion for maximum benefit.', 13.86, 5),
(285, 'Dumbbell Incline Forearms Extension', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 11.44, 11),
(286, 'Medicine Ball Reverse Hamstrings Raise', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 7.57, 7),
(287, 'Resistance Band Glutes Extension', 'Resistance Band', 'Breathe out on the exertion phase and inhale on the way down.', 13.35, 9),
(288, 'Barbell Shoulders Row', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 6.81, 3),
(289, 'Bodyweight Glutes Fly', 'Bodyweight', 'Breathe out on the exertion phase and inhale on the way down.', 10.99, 9),
(290, 'Medicine Ball Flat Hamstrings Kickback', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 7.95, 7),
(291, 'Medicine Ball Quadriceps Kickback', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 7.38, 6),
(292, 'Dumbbell Single-Arm Quadriceps Row', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 10.35, 6),
(293, 'Resistance Band Traps Row', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 6.67, 12),
(294, 'Machine Lats Shrug', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 6.92, 13),
(295, 'Machine Calves Hold', 'Machine', 'Ensure full range of motion for maximum benefit.', 8.93, 8),
(296, 'Kettlebell Reverse Forearms Crunch', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 12.32, 11),
(297, 'Medicine Ball Standing Traps Deadlift', 'Medicine Ball', 'Perform the movement in a slow, controlled manner.', 11.97, 12),
(298, 'Machine Standing Forearms Crunch', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 6.92, 11),
(299, 'Medicine Ball Reverse Shoulders Raise', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 9.02, 3),
(300, 'Kettlebell Seated Calves Row', 'Kettlebell', 'Maintain proper form and control the weight.', 10.17, 8),
(301, 'Resistance Band Chest Curl', 'Resistance Band', 'Breathe out on the exertion phase and inhale on the way down.', 7.04, 1),
(302, 'Kettlebell Single-Leg Back Curl', 'Kettlebell', 'Keep your core tight and back straight during the movement.', 7.73, 2),
(303, 'Cable Seated Biceps Curl', 'Cable', 'Keep your core tight and back straight during the movement.', 3.51, 4),
(304, 'Resistance Band Core Row', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 14.45, 10),
(305, 'Barbell Chest Raise', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 12.76, 1),
(306, 'Kettlebell Calves Pull-down', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 11.11, 8),
(307, 'Barbell Seated Glutes Pull-down', 'Barbell', 'Keep your elbows tucked in and avoid swinging.', 5.5, 9),
(308, 'Cable Seated Glutes Extension', 'Cable', 'Ensure full range of motion for maximum benefit.', 3.35, 9),
(309, 'Medicine Ball Close-Grip Calves Row', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 4.67, 8),
(310, 'Smith Machine Calves Hold', 'Smith Machine', 'Keep your elbows tucked in and avoid swinging.', 13.69, 8),
(311, 'Medicine Ball Incline Quadriceps Lunge', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 3.11, 6),
(312, 'Dumbbell Standing Calves Fly', 'Dumbbell', 'Maintain proper form and control the weight.', 7.92, 8),
(313, 'Barbell Forearms Push-down', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 10.79, 11),
(314, 'Smith Machine Single-Leg Biceps Crunch', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 9.01, 4),
(315, 'Barbell Forearms Crunch', 'Barbell', 'Ensure full range of motion for maximum benefit.', 9.76, 11),
(316, 'Barbell Glutes Deadlift', 'Barbell', 'Perform the movement in a slow, controlled manner.', 14.23, 9),
(317, 'Cable Triceps Curl', 'Cable', 'Keep your core tight and back straight during the movement.', 13.07, 5),
(318, 'Smith Machine Wide-Grip Biceps Raise', 'Smith Machine', 'Keep your elbows tucked in and avoid swinging.', 9.41, 4),
(319, 'Resistance Band Standing Triceps Deadlift', 'Resistance Band', 'Maintain proper form and control the weight.', 9.62, 5),
(320, 'Dumbbell Seated Forearms Extension', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 10.19, 11),
(321, 'Barbell Calves Row', 'Barbell', 'Ensure full range of motion for maximum benefit.', 5.69, 8),
(322, 'Bodyweight Triceps Raise', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 5.18, 5),
(323, 'Resistance Band Single-Arm Hamstrings Raise', 'Resistance Band', 'Maintain proper form and control the weight.', 11.26, 7),
(324, 'Smith Machine Glutes Press', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 4.94, 9),
(325, 'Dumbbell Single-Leg Core Kickback', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 5.64, 10),
(326, 'Medicine Ball Hamstrings Squat', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 7.02, 7),
(327, 'Kettlebell Alternating Forearms Extension', 'Kettlebell', 'Keep your core tight and back straight during the movement.', 3.53, 11),
(328, 'Dumbbell Triceps Deadlift', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 12.97, 5),
(329, 'Medicine Ball Shoulders Shrug', 'Medicine Ball', 'Perform the movement in a slow, controlled manner.', 6.89, 3),
(330, 'Smith Machine Forearms Curl', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 14.94, 11),
(331, 'Resistance Band Wide-Grip Triceps Hold', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 3.78, 5),
(332, 'Medicine Ball Seated Hamstrings Lunge', 'Medicine Ball', 'Maintain proper form and control the weight.', 12.43, 7),
(333, 'Machine Biceps Row', 'Machine', 'Keep your core tight and back straight during the movement.', 14.73, 4),
(334, 'Barbell Core Shrug', 'Barbell', 'Maintain proper form and control the weight.', 5.6, 10),
(335, 'Machine Seated Lats Press', 'Machine', 'Breathe out on the exertion phase and inhale on the way down.', 9.79, 13),
(336, 'Bodyweight Single-Leg Forearms Row', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 10.51, 11),
(337, 'Cable Flat Hamstrings Squat', 'Cable', 'Breathe out on the exertion phase and inhale on the way down.', 11.76, 7),
(338, 'Resistance Band Reverse Shoulders Extension', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 4.92, 3),
(339, 'Resistance Band Calves Deadlift', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 12.68, 8),
(340, 'Resistance Band Single-Arm Back Kickback', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 10.08, 2),
(341, 'Dumbbell Incline Forearms Fly', 'Dumbbell', 'Maintain proper form and control the weight.', 10.81, 11),
(342, 'Resistance Band Seated Quadriceps Row', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 10.84, 6),
(343, 'Dumbbell Triceps Extension', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 4.87, 5),
(344, 'Machine Calves Raise', 'Machine', 'Breathe out on the exertion phase and inhale on the way down.', 9.02, 8),
(345, 'Dumbbell Wide-Grip Glutes Extension', 'Dumbbell', 'Ensure full range of motion for maximum benefit.', 13.1, 9),
(346, 'Bodyweight Single-Leg Shoulders Row', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 12.63, 3),
(347, 'Kettlebell Single-Arm Chest Fly', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 5.8, 1),
(348, 'Smith Machine Wide-Grip Core Curl', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 7.33, 10),
(349, 'Smith Machine Reverse Lats Crunch', 'Smith Machine', 'Breathe out on the exertion phase and inhale on the way down.', 12.05, 13),
(350, 'Medicine Ball Glutes Crunch', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 8.21, 9),
(351, 'Barbell Calves Lunge', 'Barbell', 'Maintain proper form and control the weight.', 5.74, 8),
(352, 'Smith Machine Biceps Shrug', 'Smith Machine', 'Maintain proper form and control the weight.', 4.09, 4),
(353, 'Bodyweight Standing Forearms Fly', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 3.92, 11),
(354, 'Smith Machine Flat Hamstrings Row', 'Smith Machine', 'Ensure full range of motion for maximum benefit.', 10.76, 7),
(355, 'Machine Hamstrings Fly', 'Machine', 'Squeeze the target muscle at the top of the movement.', 13.07, 7),
(356, 'Bodyweight Reverse Shoulders Curl', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 9.27, 3),
(357, 'Smith Machine Reverse Triceps Extension', 'Smith Machine', 'Keep your elbows tucked in and avoid swinging.', 8.93, 5),
(358, 'Smith Machine Decline Biceps Curl', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 5.09, 4),
(359, 'Resistance Band Traps Hold', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 5.23, 12),
(360, 'Resistance Band Flat Shoulders Raise', 'Resistance Band', 'Maintain proper form and control the weight.', 10.83, 3),
(361, 'Resistance Band Core Shrug', 'Resistance Band', 'Maintain proper form and control the weight.', 12.83, 10),
(362, 'Barbell Forearms Hold', 'Barbell', 'Ensure full range of motion for maximum benefit.', 8.27, 11),
(363, 'Dumbbell Biceps Row', 'Dumbbell', 'Keep your core tight and back straight during the movement.', 9.08, 4),
(364, 'Bodyweight Decline Triceps Hold', 'Bodyweight', 'Perform the movement in a slow, controlled manner.', 7.36, 5),
(365, 'Machine Forearms Shrug', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 9.41, 11),
(366, 'Machine Reverse Shoulders Extension', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 7.26, 3),
(367, 'Medicine Ball Calves Lunge', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 12.78, 8),
(368, 'Bodyweight Biceps Row', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 12.3, 4),
(369, 'Smith Machine Alternating Shoulders Press', 'Smith Machine', 'Maintain proper form and control the weight.', 6.17, 3),
(370, 'Medicine Ball Single-Arm Triceps Crunch', 'Medicine Ball', 'Maintain proper form and control the weight.', 10.18, 5),
(371, 'Resistance Band Calves Lunge', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 7.48, 8),
(372, 'Barbell Alternating Chest Kickback', 'Barbell', 'Maintain proper form and control the weight.', 10.9, 1),
(373, 'Bodyweight Core Press', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 3.62, 10),
(374, 'Machine Forearms Fly', 'Machine', 'Keep your core tight and back straight during the movement.', 10.8, 11),
(375, 'Resistance Band Alternating Shoulders Fly', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 7.17, 3),
(376, 'Dumbbell Lats Press', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 11.64, 13),
(377, 'Bodyweight Seated Triceps Squat', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 8.2, 5),
(378, 'Medicine Ball Triceps Raise', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 14.73, 5),
(379, 'Resistance Band Flat Back Row', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 10.54, 2),
(380, 'Cable Seated Glutes Fly', 'Cable', 'Breathe out on the exertion phase and inhale on the way down.', 11.0, 9),
(381, 'Smith Machine Incline Lats Extension', 'Smith Machine', 'Maintain proper form and control the weight.', 5.33, 13),
(382, 'Medicine Ball Glutes Hold', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 4.08, 9),
(383, 'Machine Core Curl', 'Machine', 'Ensure full range of motion for maximum benefit.', 3.29, 10),
(384, 'Kettlebell Flat Chest Extension', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 5.32, 1),
(385, 'Dumbbell Glutes Press', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 3.09, 9),
(386, 'Kettlebell Calves Squat', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 6.57, 8),
(387, 'Smith Machine Core Crunch', 'Smith Machine', 'Squeeze the target muscle at the top of the movement.', 5.47, 10),
(388, 'Kettlebell Alternating Chest Curl', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 10.76, 1),
(389, 'Medicine Ball Biceps Extension', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 3.41, 4),
(390, 'Resistance Band Calves Extension', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 10.03, 8),
(391, 'Machine Forearms Deadlift', 'Machine', 'Perform the movement in a slow, controlled manner.', 9.1, 11),
(392, 'Resistance Band Hamstrings Hold', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 11.31, 7),
(393, 'Kettlebell Incline Forearms Row', 'Kettlebell', 'Maintain proper form and control the weight.', 14.28, 11),
(394, 'Cable Reverse Back Push-down', 'Cable', 'Squeeze the target muscle at the top of the movement.', 6.43, 2),
(395, 'Barbell Wide-Grip Hamstrings Squat', 'Barbell', 'Perform the movement in a slow, controlled manner.', 7.93, 7),
(396, 'Medicine Ball Close-Grip Calves Extension', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 14.54, 8),
(397, 'Dumbbell Single-Arm Forearms Hold', 'Dumbbell', 'Ensure full range of motion for maximum benefit.', 3.23, 11),
(398, 'Bodyweight Chest Press', 'Bodyweight', 'Breathe out on the exertion phase and inhale on the way down.', 5.06, 1),
(399, 'Cable Calves Row', 'Cable', 'Maintain proper form and control the weight.', 13.58, 8),
(400, 'Kettlebell Close-Grip Calves Crunch', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 5.52, 8),
(401, 'Medicine Ball Glutes Kickback', 'Medicine Ball', 'Keep your elbows tucked in and avoid swinging.', 4.57, 9),
(402, 'Bodyweight Triceps Squat', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 8.65, 5),
(403, 'Dumbbell Wide-Grip Triceps Push-down', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 6.46, 5),
(404, 'Machine Reverse Quadriceps Hold', 'Machine', 'Squeeze the target muscle at the top of the movement.', 4.66, 6),
(405, 'Medicine Ball Flat Glutes Push-down', 'Medicine Ball', 'Maintain proper form and control the weight.', 6.45, 9),
(406, 'Machine Lats Row', 'Machine', 'Ensure full range of motion for maximum benefit.', 12.45, 13),
(407, 'Kettlebell Reverse Shoulders Shrug', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 12.28, 3),
(408, 'Cable Triceps Squat', 'Cable', 'Perform the movement in a slow, controlled manner.', 8.29, 5),
(409, 'Bodyweight Hamstrings Deadlift', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 13.73, 7),
(410, 'Kettlebell Single-Leg Chest Lunge', 'Kettlebell', 'Maintain proper form and control the weight.', 5.2, 1),
(411, 'Medicine Ball Glutes Shrug', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 8.22, 9),
(412, 'Kettlebell Core Fly', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 9.05, 10),
(413, 'Kettlebell Close-Grip Biceps Lunge', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 11.44, 4),
(414, 'Cable Lats Crunch', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 13.12, 13),
(415, 'Dumbbell Decline Chest Row', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 13.14, 1),
(416, 'Barbell Traps Squat', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 7.54, 12),
(417, 'Smith Machine Single-Arm Chest Shrug', 'Smith Machine', 'Maintain proper form and control the weight.', 6.26, 1),
(418, 'Machine Calves Shrug', 'Machine', 'Ensure full range of motion for maximum benefit.', 8.86, 8),
(419, 'Barbell Lats Row', 'Barbell', 'Breathe out on the exertion phase and inhale on the way down.', 8.06, 13),
(420, 'Machine Traps Kickback', 'Machine', 'Maintain proper form and control the weight.', 11.93, 12),
(421, 'Dumbbell Back Lunge', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 10.46, 2),
(422, 'Medicine Ball Core Squat', 'Medicine Ball', 'Squeeze the target muscle at the top of the movement.', 11.88, 10),
(423, 'Barbell Standing Shoulders Crunch', 'Barbell', 'Keep your elbows tucked in and avoid swinging.', 5.67, 3),
(424, 'Kettlebell Forearms Lunge', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 12.63, 11),
(425, 'Smith Machine Wide-Grip Core Shrug', 'Smith Machine', 'Perform the movement in a slow, controlled manner.', 10.97, 10),
(426, 'Kettlebell Quadriceps Row', 'Kettlebell', 'Breathe out on the exertion phase and inhale on the way down.', 4.0, 6),
(427, 'Bodyweight Lats Kickback', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 14.75, 13),
(428, 'Kettlebell Close-Grip Traps Crunch', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 14.45, 12),
(429, 'Smith Machine Seated Shoulders Push-down', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 4.7, 3),
(430, 'Cable Hamstrings Lunge', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 8.38, 7),
(431, 'Medicine Ball Alternating Glutes Pull-down', 'Medicine Ball', 'Breathe out on the exertion phase and inhale on the way down.', 12.05, 9),
(432, 'Resistance Band Alternating Back Fly', 'Resistance Band', 'Maintain proper form and control the weight.', 14.06, 2),
(433, 'Medicine Ball Biceps Hold', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 5.7, 4),
(434, 'Dumbbell Hamstrings Raise', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 11.74, 7),
(435, 'Dumbbell Flat Glutes Fly', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 5.26, 9),
(436, 'Machine Flat Forearms Crunch', 'Machine', 'Keep your core tight and back straight during the movement.', 12.71, 11),
(437, 'Bodyweight Incline Glutes Fly', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 13.63, 9),
(438, 'Machine Glutes Shrug', 'Machine', 'Keep your elbows tucked in and avoid swinging.', 4.16, 9),
(439, 'Cable Biceps Press', 'Cable', 'Perform the movement in a slow, controlled manner.', 4.62, 4),
(440, 'Machine Flat Quadriceps Shrug', 'Machine', 'Maintain proper form and control the weight.', 11.92, 6),
(441, 'Kettlebell Standing Chest Fly', 'Kettlebell', 'Keep your elbows tucked in and avoid swinging.', 6.61, 1),
(442, 'Machine Lats Squat', 'Machine', 'Maintain proper form and control the weight.', 14.57, 13),
(443, 'Resistance Band Incline Calves Fly', 'Resistance Band', 'Keep your core tight and back straight during the movement.', 5.88, 8),
(444, 'Dumbbell Back Crunch', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 12.34, 2),
(445, 'Kettlebell Single-Arm Calves Crunch', 'Kettlebell', 'Squeeze the target muscle at the top of the movement.', 3.49, 8),
(446, 'Resistance Band Traps Fly', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 5.69, 12),
(447, 'Dumbbell Wide-Grip Calves Squat', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 6.3, 8),
(448, 'Resistance Band Decline Chest Crunch', 'Resistance Band', 'Maintain proper form and control the weight.', 6.55, 1),
(449, 'Resistance Band Glutes Row', 'Resistance Band', 'Squeeze the target muscle at the top of the movement.', 14.22, 9),
(450, 'Medicine Ball Lats Lunge', 'Medicine Ball', 'Ensure full range of motion for maximum benefit.', 9.79, 13),
(451, 'Cable Traps Hold', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 8.19, 12),
(452, 'Medicine Ball Calves Deadlift', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 9.38, 8),
(453, 'Kettlebell Hamstrings Fly', 'Kettlebell', 'Perform the movement in a slow, controlled manner.', 14.77, 7),
(454, 'Cable Core Push-down', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 4.65, 10),
(455, 'Cable Alternating Chest Hold', 'Cable', 'Ensure full range of motion for maximum benefit.', 13.62, 1),
(456, 'Barbell Glutes Lunge', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 8.51, 9),
(457, 'Cable Standing Lats Hold', 'Cable', 'Perform the movement in a slow, controlled manner.', 5.65, 13),
(458, 'Dumbbell Core Curl', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 11.78, 10),
(459, 'Resistance Band Alternating Core Curl', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 5.63, 10),
(460, 'Machine Shoulders Lunge', 'Machine', 'Squeeze the target muscle at the top of the movement.', 6.02, 3),
(461, 'Medicine Ball Quadriceps Extension', 'Medicine Ball', 'Keep your core tight and back straight during the movement.', 12.85, 6),
(462, 'Smith Machine Back Deadlift', 'Smith Machine', 'Keep your core tight and back straight during the movement.', 8.52, 2),
(463, 'Machine Single-Leg Shoulders Row', 'Machine', 'Ensure full range of motion for maximum benefit.', 10.3, 3),
(464, 'Bodyweight Single-Arm Lats Deadlift', 'Bodyweight', 'Keep your elbows tucked in and avoid swinging.', 11.36, 13),
(465, 'Kettlebell Reverse Quadriceps Push-down', 'Kettlebell', 'Maintain proper form and control the weight.', 11.92, 6),
(466, 'Barbell Shoulders Hold', 'Barbell', 'Squeeze the target muscle at the top of the movement.', 9.84, 3),
(467, 'Smith Machine Quadriceps Fly', 'Smith Machine', 'Maintain proper form and control the weight.', 9.49, 6),
(468, 'Resistance Band Single-Arm Back Hold', 'Resistance Band', 'Maintain proper form and control the weight.', 10.88, 2),
(469, 'Dumbbell Triceps Lunge', 'Dumbbell', 'Maintain proper form and control the weight.', 8.49, 5),
(470, 'Kettlebell Reverse Triceps Push-down', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 3.94, 5),
(471, 'Kettlebell Single-Leg Biceps Kickback', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 13.67, 4),
(472, 'Barbell Hamstrings Hold', 'Barbell', 'Perform the movement in a slow, controlled manner.', 12.17, 7),
(473, 'Dumbbell Flat Calves Fly', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 8.57, 8),
(474, 'Kettlebell Reverse Quadriceps Pull-down', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 3.68, 6),
(475, 'Machine Single-Leg Biceps Lunge', 'Machine', 'Perform the movement in a slow, controlled manner.', 6.2, 4),
(476, 'Resistance Band Wide-Grip Lats Curl', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 4.94, 13),
(477, 'Resistance Band Lats Extension', 'Resistance Band', 'Keep your elbows tucked in and avoid swinging.', 3.36, 13),
(478, 'Bodyweight Decline Shoulders Fly', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 5.59, 3),
(479, 'Resistance Band Lats Curl', 'Resistance Band', 'Maintain proper form and control the weight.', 4.62, 13),
(480, 'Cable Calves Extension', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 14.17, 8),
(481, 'Smith Machine Lats Extension', 'Smith Machine', 'Ensure full range of motion for maximum benefit.', 7.32, 13),
(482, 'Resistance Band Back Squat', 'Resistance Band', 'Ensure full range of motion for maximum benefit.', 12.52, 2),
(483, 'Bodyweight Glutes Extension', 'Bodyweight', 'Squeeze the target muscle at the top of the movement.', 8.68, 9),
(484, 'Machine Biceps Curl', 'Machine', 'Breathe out on the exertion phase and inhale on the way down.', 12.61, 4),
(485, 'Resistance Band Close-Grip Back Raise', 'Resistance Band', 'Perform the movement in a slow, controlled manner.', 5.47, 2),
(486, 'Cable Single-Leg Chest Kickback', 'Cable', 'Squeeze the target muscle at the top of the movement.', 13.55, 1),
(487, 'Bodyweight Core Fly', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 5.68, 10),
(488, 'Bodyweight Lats Deadlift', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 7.37, 13),
(489, 'Barbell Forearms Kickback', 'Barbell', 'Ensure full range of motion for maximum benefit.', 14.6, 11),
(490, 'Kettlebell Flat Biceps Kickback', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 13.86, 4),
(491, 'Dumbbell Single-Arm Forearms Pull-down', 'Dumbbell', 'Perform the movement in a slow, controlled manner.', 5.96, 11),
(492, 'Cable Hamstrings Row', 'Cable', 'Breathe out on the exertion phase and inhale on the way down.', 10.88, 7),
(493, 'Dumbbell Single-Leg Chest Row', 'Dumbbell', 'Keep your elbows tucked in and avoid swinging.', 12.22, 1),
(494, 'Dumbbell Close-Grip Glutes Curl', 'Dumbbell', 'Squeeze the target muscle at the top of the movement.', 3.21, 9),
(495, 'Bodyweight Single-Leg Forearms Push-down', 'Bodyweight', 'Ensure full range of motion for maximum benefit.', 8.62, 11),
(496, 'Cable Hamstrings Deadlift', 'Cable', 'Keep your elbows tucked in and avoid swinging.', 12.47, 7),
(497, 'Kettlebell Flat Triceps Shrug', 'Kettlebell', 'Ensure full range of motion for maximum benefit.', 12.48, 5),
(498, 'Bodyweight Calves Pull-down', 'Bodyweight', 'Maintain proper form and control the weight.', 14.59, 8),
(499, 'Dumbbell Biceps Fly', 'Dumbbell', 'Ensure full range of motion for maximum benefit.', 5.71, 4),
(500, 'Cable Core Deadlift', 'Cable', 'Squeeze the target muscle at the top of the movement.', 3.4, 10);
